# Generated by Django 4.1 on 2022-09-14 07:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("views", models.IntegerField(default=0, verbose_name="بازدیدها")),
                (
                    "video",
                    models.FileField(
                        upload_to=videos.models.create_videos_path,
                        verbose_name="فایل ویدئو",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=videos.models.create_cover_image_path,
                        verbose_name="کاور ویدئو",
                    ),
                ),
                ("duration", models.DurationField(verbose_name="طول ویدئو")),
                ("description", ckeditor.fields.RichTextField(verbose_name="توضیحات")),
                ("published_at", models.DateField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="teachers.teacher",
                        verbose_name="استاد",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدئو",
                "verbose_name_plural": "ویدئو ها",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "url",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="عنوان برای URL"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="videos.category",
                        verbose_name="والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
            },
        ),
    ]
