# Generated by Django 4.1 on 2022-09-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
