# Generated by Django 4.1 on 2022-09-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_remove_video_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="videos.category",
                verbose_name="دسته بندی",
            ),
            preserve_default=False,
        ),
    ]
