# Generated by Django 4.1 on 2022-09-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userip_options_alter_userip_user_ip"),
        ("videos", "0002_video_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="views",
        ),
        migrations.AddField(
            model_name="video",
            name="viewers_by_ip",
            field=models.ManyToManyField(
                blank=True,
                default="192.168.0.1",
                to="accounts.userip",
                verbose_name="بازدیدکنندگان بر اساس IP",
            ),
        ),
    ]
