# Generated by Django 4.1 on 2022-08-21 13:47

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.create_image_path_user,
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("is_admin", models.BooleanField(default=False, verbose_name="مدیر")),
            ],
            options={
                "verbose_name": "حساب",
                "verbose_name_plural": "حساب ها",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=250, unique=True)),
                ("title", models.CharField(max_length=250, null=True)),
                ("about", models.TextField(null=True)),
                ("instagram", models.CharField(max_length=250, null=True)),
                ("twitter", models.CharField(max_length=250, null=True)),
                ("github", models.CharField(max_length=250, null=True)),
                ("gitlab", models.CharField(max_length=250, null=True)),
                ("linkedin", models.CharField(max_length=250, null=True)),
                ("telegram", models.CharField(max_length=250, null=True)),
                ("email", models.EmailField(max_length=255, null=True, unique=True)),
                ("website", models.URLField(null=True)),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.create_resume_path_teacher,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "استاد",
                "verbose_name_plural": "اساتید",
            },
        ),
    ]
