# Generated by Django 4.1 on 2022-09-14 11:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        editable=False,
                        max_length=6,
                        null=True,
                        verbose_name="کد یکبار مصرف",
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(default=False, verbose_name="تلفن تایید شده"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="ایمیل تایید شده"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.create_image_path_user,
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("is_admin", models.BooleanField(default=False, verbose_name="مدیر")),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
    ]
