# Generated by Django 4.1 on 2022-08-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp_code",
            field=models.CharField(
                editable=False, max_length=6, null=True, verbose_name="کد یکبار مصرف"
            ),
        ),
    ]
