# Generated by Django 4.1 on 2022-09-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userip_options_alter_userip_user_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockUserIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocked_ip", models.GenericIPAddressField(verbose_name="IP کاربر")),
            ],
            options={
                "verbose_name": "IP مسدود",
                "verbose_name_plural": "IP های مسدود",
            },
        ),
    ]
