# Generated by Django 4.1 on 2022-09-14 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teachers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="نام کاربری"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="درباره"),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="اینستاگرام"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="توییتر"
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="گیت هاب"
                    ),
                ),
                (
                    "gitlab",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="گیت لب"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="لینکدین"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="تلگرام"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="ایمیل (پروفایل)",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="وبسایت"),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=teachers.models.create_resume_path_teacher,
                        verbose_name="فایل رزومه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "استاد",
                "verbose_name_plural": "اساتید",
            },
        ),
    ]
